### ISSUE TITLE
How do you use this?

### ISSUE THREAD

**Issue by Zaeems** [spacecodee/microsoft_teams_redesign#1]

**Comment by spacecodee** [comment]
Hi, if you need use this, in the file readme.md, are the step.
I'm used Intellij Idea as IDE.

**Comment by Zaeems** [comment]
Thanks, managed to get it to launch. 

Had to remove the mvn clean from the launch commands and launch with only javafx:run 

![image](https://user-images.githubusercontent.com/46079004/161939890-a92e636c-bc19-445c-987f-3139e10c312a.png)

**Comment by spacecodee** [comment]
Great, good luck!
